### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by androsland**
* Converted contact us to a function

### CODE REVIEW

**Comment by androsland** [comment]
please wait. dont merge yet

**Comment by androsland** [comment]
@mamchenkov please review and merge this. vital new release!

**Comment by mamchenkov** [comment]
@androsland why is your email in the contact-us?  You gonna get a lot of SPAM soon.  It should be either site's admin email, or something like that.

**Comment by androsland** [comment]
wow! i didn't notice ... sorry. lemme revise

**Comment by androsland** [comment]
@mamchenkov replaced it with text. no email.

**Pull request merged**
